version: '3.9'

services:
  db:
    image: postgres:16
    container_name: altaa-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: altaa_user
      POSTGRES_PASSWORD: altaa_pass
      POSTGRES_DB: altaa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U altaa_user -d altaa_db"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
